// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHkGAXg-Le1Udwzk5rjmDvjiosqWh-hU',
    appId: '1:112004068815:web:1cc51c7d062c695f5fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    authDomain: 'fir-auth-6789b.firebaseapp.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
    measurementId: 'G-2TZDDNJ8RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsOyU8boVrgzcDgZOTlqMd_EFsZXI_wg',
    appId: '1:112004068815:android:751059fd39a25fce5fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    storageBucket: 'fir-auth-6789b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dqoStjtrB6l2xkQT61MRzHmk-tTrPRM',
    appId: '1:112004068815:ios:e359a48135c3d4245fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    storageBucket: 'fir-auth-6789b.appspot.com',
    iosBundleId: 'com.example.newsAssignments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7dqoStjtrB6l2xkQT61MRzHmk-tTrPRM',
    appId: '1:112004068815:ios:b3685b67d7114f875fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    storageBucket: 'fir-auth-6789b.appspot.com',
    iosBundleId: 'com.example.newsAssignments.RunnerTests',
  );
}
